parameters:
    rx.endpoint: '%env(RX_ENDPOINT)%'
    rx.dbname: '%env(RX_DB_NAME)%'
services:
    Pik\Reindexer\Client\ClientInterface:
        class: Pik\Reindexer\Client\Client
        arguments:
            $endpoint: '%rx.endpoint%'
            $dbname: '%rx.dbname%'

    Pik\Reindexer\Model\ModelInterface:
        class: Pik\Reindexer\Model\Model
        autowire: true

    pik.reindexer.client:
        alias: Pik\Reindexer\Client\ClientInterface
        public: true

    pik.reindexer.model:
        alias: Pik\Reindexer\Model\ModelInterface
        public: true